[package]
name = "automata-to-graphviz"
version = "0.1.0"
authors = ["Edgar Onghena <46636609+edgarogh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
