[package]
name = "eoautomata-web"
version = "0.1.0"
authors = ["Edgar Onghena <dev@edgar.bzh>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "*"
eoautomata-core = { path = "../core" }
wasm-bindgen = "0.2"
